[package]
name = "viassic_client"
version = "0.1.0"
edition = "2021"
default-run = "viassic_client"

[dependencies]
bevy.workspace=true
vinox_voxel.workspace = true
viassic_common = {path = "../viassic_common"}
bevy-inspector-egui = "0.18.3"
ahash = "0.8.3"
bevy_flycam = "0.10.1"
